const data = {
    booksArray: [
        ["A Traveler in Time", "https://static.wikia.nocookie.net/dayz_gamepedia/images/5/57/A_Traveller_In_Time.png"],
        ["Around the World in 80 Days", "https://static.wikia.nocookie.net/dayz_gamepedia/images/1/10/Around_the_World_in_80_Days.png"],
        ["Bila nemoc", "https://static.wikia.nocookie.net/dayz_gamepedia/images/f/f1/Bila_Nemoc.png"],
        ["Crime and Punishment", "https://static.wikia.nocookie.net/dayz_gamepedia/images/d/dd/Crime_And_Punishment.png"],
        ["Die Verwandlung", "https://static.wikia.nocookie.net/dayz_gamepedia/images/7/70/Die_Verwandlung.png"],
        ["Fairy Tales", "https://static.wikia.nocookie.net/dayz_gamepedia/images/9/95/Fairy_Tales.png"],
        ["Robinson Crusoe", "https://static.wikia.nocookie.net/dayz_gamepedia/images/0/01/Robinson_Crusoe.png"],
        ["Russian learning book", "https://static.wikia.nocookie.net/dayz_gamepedia/images/3/3a/Learning_Russian.png"],
        ["Russian cheat sheet", "https://static.wikia.nocookie.net/dayz_gamepedia/images/c/c2/Russian_Cheat_Sheet.png"],
        ["Tony and the Beetles", "https://static.wikia.nocookie.net/dayz_gamepedia/images/e/e1/Tony_and_the_Beetles.png"],
        ["Youth", "https://static.wikia.nocookie.net/dayz_gamepedia/images/c/ce/Youth.png"],
        ["The Art Of War", "https://static.wikia.nocookie.net/dayz_gamepedia/images/3/3c/The_Art_Of_War.png"],
        ["The Bible", "https://static.wikia.nocookie.net/dayz_gamepedia/images/9/98/The_Bible.png"],
        ["The Brothers Karamazov", "https://static.wikia.nocookie.net/dayz_gamepedia/images/1/1a/The_Brothers_Karamazov.png"],
        ["The Barrier", "https://static.wikia.nocookie.net/dayz_gamepedia/images/f/f2/The_Barrier.png"],
        ["The Call of Cthulhu", "https://static.wikia.nocookie.net/dayz_gamepedia/images/7/78/The_Call_of_Cthulhu.png"],
        ["The Country of the Blind", "https://static.wikia.nocookie.net/dayz_gamepedia/images/7/77/The_Country_of_the_Blind.png"],
        ["The Cosmic Computer", "https://static.wikia.nocookie.net/dayz_gamepedia/images/7/74/The_Cosmic_Conputer.png"],
        ["The Desert of Wheat", "https://static.wikia.nocookie.net/dayz_gamepedia/images/c/c5/The_Desert_of_Wheat.png"],
        ["The Hound of the Baskervilles", "https://static.wikia.nocookie.net/dayz_gamepedia/images/1/17/The_Hound_of_the_Baskervilles.png"],
        ["The Jungle Book", "https://static.wikia.nocookie.net/dayz_gamepedia/images/c/cb/The_Jungle_Book.png"],
        ["The Metamorphosis", "https://static.wikia.nocookie.net/dayz_gamepedia/images/b/b6/The_Metamorphosis.png"],
        ["The Outlet", "https://static.wikia.nocookie.net/dayz_gamepedia/images/7/76/The_Outlet.png"],
        ["The Picture Of Dorian Gray", "https://static.wikia.nocookie.net/dayz_gamepedia/images/3/3a/The_Picture_of_Dorian_Gray.png"],
        ["The Pit and the Pendulum", "https://static.wikia.nocookie.net/dayz_gamepedia/images/2/29/The_Pit_and_the_Pendulum.png"],
        ["The Raven", "https://static.wikia.nocookie.net/dayz_gamepedia/images/a/a3/The_Raven.png"],
        ["The Shunned House", "https://static.wikia.nocookie.net/dayz_gamepedia/images/2/24/The_Shunned_House.png"],
        ["The Time Machine", "https://static.wikia.nocookie.net/dayz_gamepedia/images/a/ab/The_Time_Machine.png"],
        ["The War of the Worlds", "https://static.wikia.nocookie.net/dayz_gamepedia/images/f/fe/The_War_of_the_Worlds.png"],
        ["The Variable Man", "https://static.wikia.nocookie.net/dayz_gamepedia/images/e/e2/The_Variable_Man.png"],
        ["20000 Lieus sous les mers", "https://static.wikia.nocookie.net/dayz_gamepedia/images/f/fe/20000_Lieues_sous_les_mers_Parts_1_and_2.png"],
        ["A Doll 's House", "https://static.wikia.nocookie.net/dayz_gamepedia/images/a/ac/A_Doll%27s_House.png"],
        ["A Princess of Mars", "https://static.wikia.nocookie.net/dayz_gamepedia/images/8/8c/A_Princess_of_Mars.png"],
        ["A Texas Matchmaker", "https://static.wikia.nocookie.net/dayz_gamepedia/images/8/82/A_Texas_Matchmaker.png"],
        ["Betty Zane", "https://static.wikia.nocookie.net/dayz_gamepedia/images/2/24/Betty_Zane.png"],
        ["Anna Karenina", "https://static.wikia.nocookie.net/dayz_gamepedia/images/1/1f/Anna_Karenina.png"],
        ["Black Jack", "https://static.wikia.nocookie.net/dayz_gamepedia/images/9/9d/Black_Jack.png"],
        ["Hopalong Cassidy 's Rustler Round-Up", "https://static.wikia.nocookie.net/dayz_gamepedia/images/a/a5/Hopalong_Cassidy%27s_Rustler_Round-Up.png"],
        ["Dead Souls", "https://static.wikia.nocookie.net/dayz_gamepedia/images/2/2c/Dead_Souls.png"],
        ["Faust: Der Tragodie erster teil", "https://static.wikia.nocookie.net/dayz_gamepedia/images/d/dc/Faust_-_Der_Trag%C3%B6die_erster_Teil.png"],
    ],

    firstInitData: {
          "A Traveler in Time": 0,
          "Around the World in 80 Days": 0,
          "Bila nemoc": 0,
          "Crime and Punishment": 0,
          "Die Verwandlung": 0,
          "Fairy Tales": 0,
          "Robinson Crusoe": 0,
          "Russian learning book": 0,
          "Russian cheat sheet": 0,
          "Tony and the Beetles": 0,
          "Youth": 0,
          "The Art Of War": 0,
          "The Bible": 0,
          "The Brothers Karamazov": 0,
          "The Barrier": 0,
          "The Call of Cthulhu": 0,
          "The Country of the Blind": 0,
          "The Cosmic Computer": 0,
          "The Desert of Wheat": 0,
          "The Hound of the Baskervilles": 0,
          "The Jungle Book": 0,
          "The Metamorphosis": 0,
          "The Outlet": 0,
          "The Picture Of Dorian Gray": 0,
          "The Pit and the Pendulum": 0,
          "The Raven": 0,
          "The Shunned House": 0,
          "The Time Machine": 0,
          "The War of the Worlds": 0,
          "The Variable Man": 0,
          "20000 Lieus sous les mers": 0,
          "A Doll 's House": 0,
          "A Princess of Mars": 0,
          "A Texas Matchmaker": 0,
          "Betty Zane": 0,
          "Anna Karenina": 0,
          "Black Jack": 0,
          "Hopalong Cassidy 's Rustler Round-Up": 0,
          "Dead Souls": 0,
          "Faust: Der Tragodie erster teil": 0,
    }
}

export default data